backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "site"
    label: "Contenu du site"
    files:
      - label: "Accueil"
        name: "accueil"
        file: "content/home.md"
        fields:
          - { label: "Titre principal", name: "hero_title", widget: "string" }
          - { label: "Message 1", name: "message1", widget: "string" }
          - { label: "Message 2", name: "message2", widget: "string" }
          - { label: "Message 3", name: "message3", widget: "string" }
